2025-02-02 19:07:32,724 INFO    MainThread:15864 [wandb_setup.py:_flush():68] Current SDK version is 0.19.2
2025-02-02 19:07:32,724 INFO    MainThread:15864 [wandb_setup.py:_flush():68] Configure stats pid to 15864
2025-02-02 19:07:32,724 INFO    MainThread:15864 [wandb_setup.py:_flush():68] Loading settings from C:\Users\SCS\.config\wandb\settings
2025-02-02 19:07:32,726 INFO    MainThread:15864 [wandb_setup.py:_flush():68] Loading settings from C:\Users\SCS\Downloads\Annotated\wandb\settings
2025-02-02 19:07:32,726 INFO    MainThread:15864 [wandb_setup.py:_flush():68] Loading settings from environment variables
2025-02-02 19:07:32,726 INFO    MainThread:15864 [wandb_init.py:_log_setup():523] Logging user logs to C:\Users\SCS\Downloads\Annotated\wandb\run-20250202_190732-f1kj6x3z\logs\debug.log
2025-02-02 19:07:32,728 INFO    MainThread:15864 [wandb_init.py:_log_setup():524] Logging internal logs to C:\Users\SCS\Downloads\Annotated\wandb\run-20250202_190732-f1kj6x3z\logs\debug-internal.log
2025-02-02 19:07:32,728 INFO    MainThread:15864 [wandb_init.py:init():641] calling init triggers
2025-02-02 19:07:32,728 INFO    MainThread:15864 [wandb_init.py:init():647] wandb.init called with sweep_config: {}
config: {}
2025-02-02 19:07:32,728 INFO    MainThread:15864 [wandb_init.py:init():674] starting backend
2025-02-02 19:07:33,334 INFO    MainThread:15864 [wandb_init.py:init():678] sending inform_init request
2025-02-02 19:07:33,466 INFO    MainThread:15864 [backend.py:_multiprocessing_setup():104] multiprocessing start_methods=spawn, using: spawn
2025-02-02 19:07:33,468 INFO    MainThread:15864 [wandb_init.py:init():693] backend started and connected
2025-02-02 19:07:33,471 INFO    MainThread:15864 [wandb_init.py:init():786] updated telemetry
2025-02-02 19:07:33,473 INFO    MainThread:15864 [wandb_init.py:init():818] communicating run to backend with 90.0 second timeout
2025-02-02 19:07:33,530 WARNING MsgRouterThr:15864 [router.py:message_loop():75] message_loop has been closed
2025-02-02 19:07:38,524 ERROR   MainThread:15864 [wandb_init.py:init():1299] error in wandb.init()
Traceback (most recent call last):
  File "C:\Users\SCS\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\wandb_init.py", line 1289, in init
    return wi.init()
           ^^^^^^^^^
  File "C:\Users\SCS\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\wandb_init.py", line 821, in init
    result = run_init_handle.wait(
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SCS\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\lib\mailbox.py", line 277, in wait
    raise MailboxError("transport failed")
wandb.sdk.lib.mailbox.MailboxError: transport failed
